name: Site Build

on:
  push:
    branches: [ restructure ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build
    - run: git diff
    - run: git config user.email "actions@reposing.net"
    - run: git config user.name "Reposiing GitHub Actions"
    - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
    - run: npm run deploy